### ISSUE TITLE
unable to run empty electron-starter project with example node-snap7 code

### ISSUE THREAD

**Issue by sabinin** [mathiask88/node-snap7#15]
version of node 0.9.9 
http://prntscr.com/b1z2te - printscreen of error

please tell me what i`m doing wrong ? :)

**Comment by mathiask88** [comment]
I don't have much experience with electron. Did you follow [this](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) guide to build the native modules?

**Comment by sabinin** [comment]
Thanks for notice, will try it.

**Comment by sabinin** [comment]
Hi, can you write please a version of node which snap7 does currently support ?

**Comment by mathiask88** [comment]
0.8, 0.10, 0.12, 3, 4, 5 and in some days 6 also.

**Comment by mathiask88** [comment]
I released a new version that supports node v6.x. Now you should be able to run newest electron starter if you `npm install` and then `electron-rebuild`.

**Comment by sabinin** [comment]
Thanks a lot, will try it today!

**Comment by mathiask88** [comment]
I tried it myself and it works, but I had to use `.\node_modules\.bin\electron-rebuild.cmd -f` on my windows machine to force `electron-rebuild` to rebuild the dependencies. I don't know why it skips some modules otherwise. I will close for now. If you have any questions left feel free to ask.
