### ISSUE TITLE
S7 Server Support?

### ISSUE THREAD

**Issue by j8** [mathiask88/node-snap7#16]
Hello,

Thank you very much for the nice lib.

This is future request, but when writing tests for app using node-snap7 it will be extremely helpful to be able to mock S7 Server.

**Comment by mathiask88** [comment]
Hi,

Nice to hear, that someone uses and likes the lib :grinning: Yes, that is on my list for too long. I think I can look into it in August.

**Comment by mathiask88** [comment]
Hey, I got a first implementation ready. A bit late but better late than never :) If you are still interested, I can publish a new branch on sunday so you can test it.

**Comment by psi-4ward** [comment]
Sadly I've currently no time to work on the project but anyways, publish 
it please! :)

**Comment by mathiask88** [comment]
Unfortunately I can't make it today, but within next week for sure.
