### ISSUE TITLE
GetAgBlockInfo() not working

### ISSUE THREAD

**Issue by Yaro96** [mathiask88/node-snap7#24]
I tried to use this function to get the DB size on a Siemens s7-300, using the callback it doesn't enter into it at all. Without the callback it just returns "false" with no errors.
[getSize.txt](https://github.com/mathiask88/node-snap7/files/865048/getSize.txt)

**Comment by mathiask88** [comment]
The function is working for me. As a side note: Returning in the callback function (`return res.MC7Size;`) will not return the value for `getDBLength()` 😉

**Comment by Yaro96** [comment]
In my case, it doesn't enter in the callback at all, it doesn't even print "I'm here!"

**Comment by mathiask88** [comment]
Are you sure that the client gets connected at all? AFAIK 300er are on slot 1 and not 2.

**Comment by Yaro96** [comment]
Yes, I'm sure it works perfectly with other functions and the Snap7 demo client.
It doesn't pop any connection errors and if I put a console.log just before the GetAgBlockInfo(), it prints.

**Comment by mathiask88** [comment]
If I can't reproduce your error I don't know how I can help you. Can you try your script with the snap7 demo server? And maybe post your node.js and node-snap7 versions?

**Comment by Yaro96** [comment]
I figured it out, it was an asyncrous request problem. Sorry for bothering you.

**Comment by mathiask88** [comment]
Good to hear, that you found it. No problem :)
