### ISSUE TITLE
S7Server.LastError is not a function

### ISSUE THREAD

**Issue by Noctua36** [mathiask88/node-snap7#26]
In the documentation of the server is described:

> **S7Server.LastError()**
> 
> Returns the last job result.

Trying to call `var err = S7Server.LastError()` raises the error:

> TypeError: S7Server.LastError is not a function

**Comment by mathiask88** [comment]
Oh, yes you are right. I missed a line of code to register that function to node.js 😆 I will patch it tomorrow, thanks!

**Comment by mathiask88** [comment]
fixed in https://github.com/mathiask88/node-snap7/commit/b9ea936f777872a2eff583b4cfe95c757bf9af8e
