### ISSUE TITLE
node-snap7 release with server

### ISSUE THREAD

**Issue by teropes** [mathiask88/node-snap7#27]
Hello,

Are there plans to bump new version of node-snap7 including new server functionality and release it to npm repository? I would like to refer to specific package version in npm instead of github master ;)

Being able to use snap7 server from Node.js is great, no need to manage server binaries separately and easier to automate testing / setup dev environment. Gj!

**Comment by mathiask88** [comment]
Yes I need to. I thought I would make it last week, but unfortunately not. I got some small bug fixes left, but I think this week is the week 😄

**Comment by mathiask88** [comment]
Published as [0.3.0](https://www.npmjs.com/package/node-snap7)
