### ISSUE TITLE
node-Crash on MacOS/hang on Win when node-snap7 is used on nodejs 4!

### ISSUE THREAD

**Issue by Apollon77** [mathiask88/node-snap7#34]
Hi,

we use node-snap7 in a project and in our Travis-CI tests on MacOS the node process crashed immediately when starting with:

Assertion failed: (object->InternalFieldCount() > 0), function Wrap, file ../node_modules/nan/nan_object_wrap.h, line 55.

https://travis-ci.org/ioBroker/ioBroker.s7/jobs/326705863#L456
I tried also "build from source", same happens there.

Any idea what causes this?

**Comment by Apollon77** [comment]
I think the crash happens in https://github.com/ioBroker/ioBroker.s7/blob/master/test/lib/s7Server.js

**Comment by Apollon77** [comment]
On Windows for node 4 (on Appveyor) it just hangs (and Appveyor kills the test after 1h) basically at the same place in code where it brings that error on MacOS (I assume)

**Comment by Apollon77** [comment]
Need to correct myself again: also happens on Linux. So irbid nodejs 4 on all platforms where this problem exists.

**Comment by Apollon77** [comment]
On Linux the error is:

node: ../node_modules/nan/nan_object_wrap.h:55: void Nan::ObjectWrap::Wrap(v8::Local<v8::Object>): Assertion `object->InternalFieldCount() > 0' failed.

**Comment by Apollon77** [comment]
Additonal Link to the Travis-ci/Appveyor tests for my project where you can see this:

Linux: https://travis-ci.org/ioBroker/ioBroker.s7/jobs/326887620#L840
MacOS: https://travis-ci.org/ioBroker/ioBroker.s7/jobs/326887626#L452
Windows: https://ci.appveyor.com/project/Apollon77/iobroker-s7/build/test-65/job/egcig2l9pa98cd63#L266 ( you only see that there is no output anymore and Appveyor killed it after 1h

**Comment by mathiask88** [comment]
@Apollon77 I'm currently searching for the reason, but I don't have any idea yet :confused:

**Comment by Apollon77** [comment]
Thank you in any case for your efforts! Hope you find the "holy gral" soon :-) I'm no C/C++ guy else I would offer help.
But you can reproduce it?

**Comment by mathiask88** [comment]
Yes I could, thanks for reporting. If I google that error I see several issues but no real solution. I will ask in nodejs/help if I can't find a cause.

**Comment by mathiask88** [comment]
Should be fixed by e0ef6406b9aa4666946ab788f5e6d2f7324a6bdd. I will release a new version this weekend.

**Comment by Apollon77** [comment]
Cool!
As soon as it is released I will update the dep in my project and verify it!

**Comment by mathiask88** [comment]
@Apollon77 You can try `1.0.0` now :)

**Comment by Apollon77** [comment]
Verified. Tests show green!! Thank you very much
