### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by hillcz** [mathiask88/node-snap7#35]
Hi 
If i try SNAP7 on LTS node 6.10.2
I have err. message  Module version mismatch. Expected 47, got 48.
Can you fix it ? 
THX

**Comment by mathiask88** [comment]
Did you change your node version or is this a fresh installation? If you change major node versions you always have to `npm rebuild `.

**Comment by Noctua36** [comment]
Are you using it with electron? If so, you can install the `electron-rebuild` package and add this script on package.json : `"postinstall": "electron-rebuild"`

**Comment by hillcz** [comment]
Nodejs was preinstaled by myscada app. node-snap7 I am installing by nmp install

**Comment by mathiask88** [comment]
@hillcz If I can't reproduce this, I can only guess what your issue is. I think it is not an issue with `node-snap7` itself but with your environment you are installing. Did you solve it?

**Comment by hillcz** [comment]
Yes I fixed it. I dont know why, but NTP VERSION return me NODE 6.10.2 and i have instaled 5.4.1.
Now it is working. Thanks for perfect module. Sorry for fake issue and my horible english .
