### ISSUE TITLE
Build error on nodejs 10 and windows

### ISSUE THREAD

**Issue by Apollon77** [mathiask88/node-snap7#40]
see: https://ci.appveyor.com/project/Apollon77/iobroker-s7/build/job/ajdglh0wjyxicds8#L35

**Comment by mathiask88** [comment]
https://github.com/mathiask88/node-snap7/tree/v1.0.1

**Comment by Apollon77** [comment]
Yes node01 now works ... but nodejs 6 no longer on all platforms!!
--> https://github.com/mathiask88/node-snap7/issues/42

**Comment by mathiask88** [comment]
This is odd. Passing on my CI at least https://travis-ci.org/mathiask88/node-snap7 :S

**Comment by Apollon77** [comment]
Strange ... BTW it only affects linux&mac ... windows works. Do you have any idea?

**Comment by Apollon77** [comment]
Ok, seems solved ... I had a "--build-from-source" in the install call and then I got that error, but now without that and using normal "npm install" that uses prebuild binaries from you everything works.
still strange, but solved for now
