### ISSUE TITLE
Do you support reading and writing of DB blocks for s7-1200?

### ISSUE THREAD

**Issue by SherryHolmes** [mathiask88/node-snap7#44]
Do you support reading and writing of DB blocks for s7-1200?Test finds read and write DB block failed 
#36700160 - CLI : function refused by CPU (Unknown error)

**Comment by mathiask88** [comment]
@SherryHolmes Reading and writing blocks is possible for the 1200/1500 CPUs but it comes with some limitations. Just read the compatibility link [here](https://github.com/mathiask88/node-snap7#about). For your problem these are the relevant information:
1.    Only global DBs can be accessed.
2.    The optimized block access must be turned off.
3.    The access level must be “full” and the “connection mechanism” must allow GET/PUT.
