### ISSUE TITLE
PLC readDB  <Pending>

### ISSUE THREAD

**Issue by anthrogan** [mathiask88/node-snap7#48]
Any reason why a PLC wouldn't respond when its requested to readDB? In particular its the 315/7? I've checked connection resource etc and can't see anything obvious it just seems to never respond after a read attempt, The issue is obviously with the PLCs but I'm kinda lost in terms of where to look!

**Comment by Johanneslueke** [comment]
If the DB is compressed reading it is not possible. Did you checked that this option is disabled?

**Comment by anthrogan** [comment]
After some investigation and a chat with a siemens integrator it's appears to be down to the 343 cards in the facilities regardless of it being a 343-1 or 343 Lean. I assumed maybe a firmware difference as both cards have the same order number but there's some suggestion to the cards being physically a little different too according to their hardware version which in my mind should really change the order number:

![image](https://user-images.githubusercontent.com/30973884/52719833-4f1ab780-2f9e-11e9-8a9a-8b36ae952ec5.png)

Oh well nevermind, I will collect data via OPC through connectivity pack instead. Hopefully this is helpful to someone!
