### ISSUE TITLE
install onto RPI with Node 12 failing

### ISSUE THREAD

**Issue by jgarvey955** [mathiask88/node-snap7#59]
Installing with NPM onto an RPI running node 12 continually fails. I have verified if I pull the repo and install local then it installs correctly.

**Comment by jgarvey955** [comment]
This happens even with --build-from-source

**Comment by mathiask88** [comment]
Should be fixed with 1.0.3. If not feel free to reopen.

**Comment by jgarvey955** [comment]
Its works now. Thank you.
