### ISSUE TITLE
Read OB & FC data ?

### ISSUE THREAD

**Issue by alirasapour** [mathiask88/node-snap7#78]
Hi guys .

i want to read data on OB1 AND FC2,3,4......

Can anyone help?

THANKS.

**Comment by mathiask88** [comment]
Have a look at the [Directory / Block orientated functions](https://github.com/mathiask88/node-snap7/blob/master/doc/client.md#api---block-oriented-functions). Please keep in mind that these functions are not available for the new 1200/1500 series. See the target compatibility in the table [here ](http://snap7.sourceforge.net/snap7_client.html#target_compatibility).

**Comment by alirasapour** [comment]
thanks
